##CREATE SEQUENCE TRAVELORDER_SEQUENCE START WITH 1 INCREMENT BY 1;
##INSERT INTO TravelOrder(id) VALUES (nextval('TRAVELORDER_SEQUENCE'));
##INSERT INTO TravelOrder(id) VALUES (nextval('TRAVELORDER_SEQUENCE'));
##INSERT INTO TravelOrder(id) VALUES (nextval('TRAVELORDER_SEQUENCE'));
##INSERT INTO TravelOrder(id) VALUES (nextval('TRAVELORDER_SEQUENCE'));
##INSERT INTO TravelOrder(id) VALUES (nextval('TRAVELORDER_SEQUENCE'));